/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AccountVelocityLimit type.
 */
public class AccountVelocityLimit {
    private String type;
    private String period;
    private Double limit;
    private Double accumulation;
    private Double balance;
    private Boolean override;
    private String productGroup;
    private Double threshold;

    /**
     * Default constructor.
     */
    public AccountVelocityLimit() {
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  period  String value for period.
     * @param  limit  Double value for limit.
     * @param  accumulation  Double value for accumulation.
     * @param  balance  Double value for balance.
     * @param  override  Boolean value for override.
     * @param  productGroup  String value for productGroup.
     * @param  threshold  Double value for threshold.
     */
    public AccountVelocityLimit(
            String type,
            String period,
            Double limit,
            Double accumulation,
            Double balance,
            Boolean override,
            String productGroup,
            Double threshold) {
        this.type = type;
        this.period = period;
        this.limit = limit;
        this.accumulation = accumulation;
        this.balance = balance;
        this.override = override;
        this.productGroup = productGroup;
        this.threshold = threshold;
    }

    /**
     * Getter for Type.
     * Type of velocity (COUNT type is not present for limits of PERTRX period Possible Values:
     * VALUE, VOLUME, COUNT
     * @return Returns the String
     */
    @JsonGetter("Type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Type of velocity (COUNT type is not present for limits of PERTRX period Possible Values:
     * VALUE, VOLUME, COUNT
     * @param type Value for String
     */
    @JsonSetter("Type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Period.
     * Duration of the velocity or threshold alert. Possible Values: DAILY, WEEKLY, MONTHLY, ANNUAL,
     * LIFETIME, PERTRX
     * @return Returns the String
     */
    @JsonGetter("Period")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPeriod() {
        return period;
    }

    /**
     * Setter for Period.
     * Duration of the velocity or threshold alert. Possible Values: DAILY, WEEKLY, MONTHLY, ANNUAL,
     * LIFETIME, PERTRX
     * @param period Value for String
     */
    @JsonSetter("Period")
    public void setPeriod(String period) {
        this.period = period;
    }

    /**
     * Getter for Limit.
     * The limit associated with this velocity with the correct number of digits after the decimal
     * point according to the minor denomination of the currency of the card issuer. Example:
     * 1500.55
     * @return Returns the Double
     */
    @JsonGetter("Limit")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getLimit() {
        return limit;
    }

    /**
     * Setter for Limit.
     * The limit associated with this velocity with the correct number of digits after the decimal
     * point according to the minor denomination of the currency of the card issuer. Example:
     * 1500.55
     * @param limit Value for Double
     */
    @JsonSetter("Limit")
    public void setLimit(Double limit) {
        this.limit = limit;
    }

    /**
     * Getter for Accumulation.
     * The transaction accumulation during the current period with the correct number of digits
     * after the decimal point according to the minor denomination of the currency of the card
     * issuer (except for COUNT type velocity). Not present for PERTRX period. Example: 1100.55
     * @return Returns the Double
     */
    @JsonGetter("Accumulation")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getAccumulation() {
        return accumulation;
    }

    /**
     * Setter for Accumulation.
     * The transaction accumulation during the current period with the correct number of digits
     * after the decimal point according to the minor denomination of the currency of the card
     * issuer (except for COUNT type velocity). Not present for PERTRX period. Example: 1100.55
     * @param accumulation Value for Double
     */
    @JsonSetter("Accumulation")
    public void setAccumulation(Double accumulation) {
        this.accumulation = accumulation;
    }

    /**
     * Getter for Balance.
     * The remaining/available balance at this point in time with the correct number of digits after
     * the decimal point according to the minor denomination of the currency of the card issuer
     * (except for COUNT type velocity). Not present for PERTRX period. Example: 400.55
     * @return Returns the Double
     */
    @JsonGetter("Balance")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getBalance() {
        return balance;
    }

    /**
     * Setter for Balance.
     * The remaining/available balance at this point in time with the correct number of digits after
     * the decimal point according to the minor denomination of the currency of the card issuer
     * (except for COUNT type velocity). Not present for PERTRX period. Example: 400.55
     * @param balance Value for Double
     */
    @JsonSetter("Balance")
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * Getter for MOverride.
     * Indicate if the limit is overridden or default. (false for default). Example: false
     * @return Returns the Boolean
     */
    @JsonGetter("Override")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getMOverride() {
        return override;
    }

    /**
     * Setter for MOverride.
     * Indicate if the limit is overridden or default. (false for default). Example: false
     * @param override Value for Boolean
     */
    @JsonSetter("Override")
    public void setMOverride(Boolean override) {
        this.override = override;
    }

    /**
     * Getter for ProductGroup.
     * The reference group name for product differentiated velocities. This field cannot be used
     * with Volume type velocity. Example: RoadSvc This is an optional output field.
     * @return Returns the String
     */
    @JsonGetter("ProductGroup")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getProductGroup() {
        return productGroup;
    }

    /**
     * Setter for ProductGroup.
     * The reference group name for product differentiated velocities. This field cannot be used
     * with Volume type velocity. Example: RoadSvc This is an optional output field.
     * @param productGroup Value for String
     */
    @JsonSetter("ProductGroup")
    public void setProductGroup(String productGroup) {
        this.productGroup = productGroup;
    }

    /**
     * Getter for Threshold.
     * The limit to trigger an alert if the balance after a transaction reaches it or below. 0
     * indicates no alerts will be sent. Not present if not set (issuer value threshold limit
     * applies if available). Not present for COUNT type velocity. Example: 50.55 This is an
     * optional output field.
     * @return Returns the Double
     */
    @JsonGetter("Threshold")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getThreshold() {
        return threshold;
    }

    /**
     * Setter for Threshold.
     * The limit to trigger an alert if the balance after a transaction reaches it or below. 0
     * indicates no alerts will be sent. Not present if not set (issuer value threshold limit
     * applies if available). Not present for COUNT type velocity. Example: 50.55 This is an
     * optional output field.
     * @param threshold Value for Double
     */
    @JsonSetter("Threshold")
    public void setThreshold(Double threshold) {
        this.threshold = threshold;
    }

    /**
     * Converts this AccountVelocityLimit into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccountVelocityLimit [" + "type=" + type + ", period=" + period + ", limit=" + limit
                + ", accumulation=" + accumulation + ", balance=" + balance + ", override="
                + override + ", productGroup=" + productGroup + ", threshold=" + threshold + "]";
    }

    /**
     * Builds a new {@link AccountVelocityLimit.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccountVelocityLimit.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .type(getType())
                .period(getPeriod())
                .limit(getLimit())
                .accumulation(getAccumulation())
                .balance(getBalance())
                .override(getMOverride())
                .productGroup(getProductGroup())
                .threshold(getThreshold());
        return builder;
    }

    /**
     * Class to build instances of {@link AccountVelocityLimit}.
     */
    public static class Builder {
        private String type;
        private String period;
        private Double limit;
        private Double accumulation;
        private Double balance;
        private Boolean override;
        private String productGroup;
        private Double threshold;



        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for period.
         * @param  period  String value for period.
         * @return Builder
         */
        public Builder period(String period) {
            this.period = period;
            return this;
        }

        /**
         * Setter for limit.
         * @param  limit  Double value for limit.
         * @return Builder
         */
        public Builder limit(Double limit) {
            this.limit = limit;
            return this;
        }

        /**
         * Setter for accumulation.
         * @param  accumulation  Double value for accumulation.
         * @return Builder
         */
        public Builder accumulation(Double accumulation) {
            this.accumulation = accumulation;
            return this;
        }

        /**
         * Setter for balance.
         * @param  balance  Double value for balance.
         * @return Builder
         */
        public Builder balance(Double balance) {
            this.balance = balance;
            return this;
        }

        /**
         * Setter for override.
         * @param  override  Boolean value for override.
         * @return Builder
         */
        public Builder override(Boolean override) {
            this.override = override;
            return this;
        }

        /**
         * Setter for productGroup.
         * @param  productGroup  String value for productGroup.
         * @return Builder
         */
        public Builder productGroup(String productGroup) {
            this.productGroup = productGroup;
            return this;
        }

        /**
         * Setter for threshold.
         * @param  threshold  Double value for threshold.
         * @return Builder
         */
        public Builder threshold(Double threshold) {
            this.threshold = threshold;
            return this;
        }

        /**
         * Builds a new {@link AccountVelocityLimit} object using the set fields.
         * @return {@link AccountVelocityLimit}
         */
        public AccountVelocityLimit build() {
            return new AccountVelocityLimit(type, period, limit, accumulation, balance, override,
                    productGroup, threshold);
        }
    }
}
