/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for BundleDetailsResponse type.
 */
public class BundleDetailsResponse {
    private Integer payerId;
    private String payerNumber;
    private Integer accountId;
    private String accountNumber;
    private String bundleId;
    private String externalBundleId;
    private String description;
    private List<String> pans;
    private String restrictionCurrencyCode;
    private String restrictionCurrencySymbol;
    private BundledRestrictionsList restrictions;
    private ErrorStatus error;
    private String requestId;

    /**
     * Default constructor.
     */
    public BundleDetailsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  payerId  Integer value for payerId.
     * @param  payerNumber  String value for payerNumber.
     * @param  accountId  Integer value for accountId.
     * @param  accountNumber  String value for accountNumber.
     * @param  bundleId  String value for bundleId.
     * @param  externalBundleId  String value for externalBundleId.
     * @param  description  String value for description.
     * @param  pans  List of String value for pans.
     * @param  restrictionCurrencyCode  String value for restrictionCurrencyCode.
     * @param  restrictionCurrencySymbol  String value for restrictionCurrencySymbol.
     * @param  restrictions  BundledRestrictionsList value for restrictions.
     * @param  error  ErrorStatus value for error.
     * @param  requestId  String value for requestId.
     */
    public BundleDetailsResponse(
            Integer payerId,
            String payerNumber,
            Integer accountId,
            String accountNumber,
            String bundleId,
            String externalBundleId,
            String description,
            List<String> pans,
            String restrictionCurrencyCode,
            String restrictionCurrencySymbol,
            BundledRestrictionsList restrictions,
            ErrorStatus error,
            String requestId) {
        this.payerId = payerId;
        this.payerNumber = payerNumber;
        this.accountId = accountId;
        this.accountNumber = accountNumber;
        this.bundleId = bundleId;
        this.externalBundleId = externalBundleId;
        this.description = description;
        this.pans = pans;
        this.restrictionCurrencyCode = restrictionCurrencyCode;
        this.restrictionCurrencySymbol = restrictionCurrencySymbol;
        this.restrictions = restrictions;
        this.error = error;
        this.requestId = requestId;
    }

    /**
     * Getter for PayerId.
     * Payer Id of the bundles and cards. Example: 123456
     * @return Returns the Integer
     */
    @JsonGetter("PayerId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPayerId() {
        return payerId;
    }

    /**
     * Setter for PayerId.
     * Payer Id of the bundles and cards. Example: 123456
     * @param payerId Value for Integer
     */
    @JsonSetter("PayerId")
    public void setPayerId(Integer payerId) {
        this.payerId = payerId;
    }

    /**
     * Getter for PayerNumber.
     * Payer Number of the bundles and cards. Example: GB000000123
     * @return Returns the String
     */
    @JsonGetter("PayerNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPayerNumber() {
        return payerNumber;
    }

    /**
     * Setter for PayerNumber.
     * Payer Number of the bundles and cards. Example: GB000000123
     * @param payerNumber Value for String
     */
    @JsonSetter("PayerNumber")
    public void setPayerNumber(String payerNumber) {
        this.payerNumber = payerNumber;
    }

    /**
     * Getter for AccountId.
     * Account ID of the bundle. Example: 123456
     * @return Returns the Integer
     */
    @JsonGetter("AccountId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * Setter for AccountId.
     * Account ID of the bundle. Example: 123456
     * @param accountId Value for Integer
     */
    @JsonSetter("AccountId")
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for AccountNumber.
     * Account Number of the bundle. Example: GB000000123
     * @return Returns the String
     */
    @JsonGetter("AccountNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Setter for AccountNumber.
     * Account Number of the bundle. Example: GB000000123
     * @param accountNumber Value for String
     */
    @JsonSetter("AccountNumber")
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Getter for BundleId.
     * unique identifier for the Card Bundle
     * @return Returns the String
     */
    @JsonGetter("BundleId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBundleId() {
        return bundleId;
    }

    /**
     * Setter for BundleId.
     * unique identifier for the Card Bundle
     * @param bundleId Value for String
     */
    @JsonSetter("BundleId")
    public void setBundleId(String bundleId) {
        this.bundleId = bundleId;
    }

    /**
     * Getter for ExternalBundleId.
     * External system allocated Card Bundle identifier for Card Bundle.
     * @return Returns the String
     */
    @JsonGetter("ExternalBundleId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExternalBundleId() {
        return externalBundleId;
    }

    /**
     * Setter for ExternalBundleId.
     * External system allocated Card Bundle identifier for Card Bundle.
     * @param externalBundleId Value for String
     */
    @JsonSetter("ExternalBundleId")
    public void setExternalBundleId(String externalBundleId) {
        this.externalBundleId = externalBundleId;
    }

    /**
     * Getter for Description.
     * Card Bundle Description.
     * @return Returns the String
     */
    @JsonGetter("Description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * Card Bundle Description.
     * @param description Value for String
     */
    @JsonSetter("Description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Pans.
     * List of Card Pans added to the card bundle.
     * @return Returns the List of String
     */
    @JsonGetter("Pans")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getPans() {
        return pans;
    }

    /**
     * Setter for Pans.
     * List of Card Pans added to the card bundle.
     * @param pans Value for List of String
     */
    @JsonSetter("Pans")
    public void setPans(List<String> pans) {
        this.pans = pans;
    }

    /**
     * Getter for RestrictionCurrencyCode.
     * ISO currency code of the country. Example: GBP
     * @return Returns the String
     */
    @JsonGetter("RestrictionCurrencyCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRestrictionCurrencyCode() {
        return restrictionCurrencyCode;
    }

    /**
     * Setter for RestrictionCurrencyCode.
     * ISO currency code of the country. Example: GBP
     * @param restrictionCurrencyCode Value for String
     */
    @JsonSetter("RestrictionCurrencyCode")
    public void setRestrictionCurrencyCode(String restrictionCurrencyCode) {
        this.restrictionCurrencyCode = restrictionCurrencyCode;
    }

    /**
     * Getter for RestrictionCurrencySymbol.
     * Currency symbol of the country. Example: £, $
     * @return Returns the String
     */
    @JsonGetter("RestrictionCurrencySymbol")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRestrictionCurrencySymbol() {
        return restrictionCurrencySymbol;
    }

    /**
     * Setter for RestrictionCurrencySymbol.
     * Currency symbol of the country. Example: £, $
     * @param restrictionCurrencySymbol Value for String
     */
    @JsonSetter("RestrictionCurrencySymbol")
    public void setRestrictionCurrencySymbol(String restrictionCurrencySymbol) {
        this.restrictionCurrencySymbol = restrictionCurrencySymbol;
    }

    /**
     * Getter for Restrictions.
     * @return Returns the BundledRestrictionsList
     */
    @JsonGetter("Restrictions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BundledRestrictionsList getRestrictions() {
        return restrictions;
    }

    /**
     * Setter for Restrictions.
     * @param restrictions Value for BundledRestrictionsList
     */
    @JsonSetter("Restrictions")
    public void setRestrictions(BundledRestrictionsList restrictions) {
        this.restrictions = restrictions;
    }

    /**
     * Getter for Error.
     * @return Returns the ErrorStatus
     */
    @JsonGetter("Error")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ErrorStatus getError() {
        return error;
    }

    /**
     * Setter for Error.
     * @param error Value for ErrorStatus
     */
    @JsonSetter("Error")
    public void setError(ErrorStatus error) {
        this.error = error;
    }

    /**
     * Getter for RequestId.
     * API Request Id
     * @return Returns the String
     */
    @JsonGetter("RequestId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRequestId() {
        return requestId;
    }

    /**
     * Setter for RequestId.
     * API Request Id
     * @param requestId Value for String
     */
    @JsonSetter("RequestId")
    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * Converts this BundleDetailsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BundleDetailsResponse [" + "payerId=" + payerId + ", payerNumber=" + payerNumber
                + ", accountId=" + accountId + ", accountNumber=" + accountNumber + ", bundleId="
                + bundleId + ", externalBundleId=" + externalBundleId + ", description="
                + description + ", pans=" + pans + ", restrictionCurrencyCode="
                + restrictionCurrencyCode + ", restrictionCurrencySymbol="
                + restrictionCurrencySymbol + ", restrictions=" + restrictions + ", error=" + error
                + ", requestId=" + requestId + "]";
    }

    /**
     * Builds a new {@link BundleDetailsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BundleDetailsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .payerId(getPayerId())
                .payerNumber(getPayerNumber())
                .accountId(getAccountId())
                .accountNumber(getAccountNumber())
                .bundleId(getBundleId())
                .externalBundleId(getExternalBundleId())
                .description(getDescription())
                .pans(getPans())
                .restrictionCurrencyCode(getRestrictionCurrencyCode())
                .restrictionCurrencySymbol(getRestrictionCurrencySymbol())
                .restrictions(getRestrictions())
                .error(getError())
                .requestId(getRequestId());
        return builder;
    }

    /**
     * Class to build instances of {@link BundleDetailsResponse}.
     */
    public static class Builder {
        private Integer payerId;
        private String payerNumber;
        private Integer accountId;
        private String accountNumber;
        private String bundleId;
        private String externalBundleId;
        private String description;
        private List<String> pans;
        private String restrictionCurrencyCode;
        private String restrictionCurrencySymbol;
        private BundledRestrictionsList restrictions;
        private ErrorStatus error;
        private String requestId;



        /**
         * Setter for payerId.
         * @param  payerId  Integer value for payerId.
         * @return Builder
         */
        public Builder payerId(Integer payerId) {
            this.payerId = payerId;
            return this;
        }

        /**
         * Setter for payerNumber.
         * @param  payerNumber  String value for payerNumber.
         * @return Builder
         */
        public Builder payerNumber(String payerNumber) {
            this.payerNumber = payerNumber;
            return this;
        }

        /**
         * Setter for accountId.
         * @param  accountId  Integer value for accountId.
         * @return Builder
         */
        public Builder accountId(Integer accountId) {
            this.accountId = accountId;
            return this;
        }

        /**
         * Setter for accountNumber.
         * @param  accountNumber  String value for accountNumber.
         * @return Builder
         */
        public Builder accountNumber(String accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }

        /**
         * Setter for bundleId.
         * @param  bundleId  String value for bundleId.
         * @return Builder
         */
        public Builder bundleId(String bundleId) {
            this.bundleId = bundleId;
            return this;
        }

        /**
         * Setter for externalBundleId.
         * @param  externalBundleId  String value for externalBundleId.
         * @return Builder
         */
        public Builder externalBundleId(String externalBundleId) {
            this.externalBundleId = externalBundleId;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for pans.
         * @param  pans  List of String value for pans.
         * @return Builder
         */
        public Builder pans(List<String> pans) {
            this.pans = pans;
            return this;
        }

        /**
         * Setter for restrictionCurrencyCode.
         * @param  restrictionCurrencyCode  String value for restrictionCurrencyCode.
         * @return Builder
         */
        public Builder restrictionCurrencyCode(String restrictionCurrencyCode) {
            this.restrictionCurrencyCode = restrictionCurrencyCode;
            return this;
        }

        /**
         * Setter for restrictionCurrencySymbol.
         * @param  restrictionCurrencySymbol  String value for restrictionCurrencySymbol.
         * @return Builder
         */
        public Builder restrictionCurrencySymbol(String restrictionCurrencySymbol) {
            this.restrictionCurrencySymbol = restrictionCurrencySymbol;
            return this;
        }

        /**
         * Setter for restrictions.
         * @param  restrictions  BundledRestrictionsList value for restrictions.
         * @return Builder
         */
        public Builder restrictions(BundledRestrictionsList restrictions) {
            this.restrictions = restrictions;
            return this;
        }

        /**
         * Setter for error.
         * @param  error  ErrorStatus value for error.
         * @return Builder
         */
        public Builder error(ErrorStatus error) {
            this.error = error;
            return this;
        }

        /**
         * Setter for requestId.
         * @param  requestId  String value for requestId.
         * @return Builder
         */
        public Builder requestId(String requestId) {
            this.requestId = requestId;
            return this;
        }

        /**
         * Builds a new {@link BundleDetailsResponse} object using the set fields.
         * @return {@link BundleDetailsResponse}
         */
        public BundleDetailsResponse build() {
            return new BundleDetailsResponse(payerId, payerNumber, accountId, accountNumber,
                    bundleId, externalBundleId, description, pans, restrictionCurrencyCode,
                    restrictionCurrencySymbol, restrictions, error, requestId);
        }
    }
}
