/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CreateBundleResponseDataItemsCardsItems type.
 */
public class CreateBundleResponseDataItemsCardsItems {
    private String pAN;

    /**
     * Default constructor.
     */
    public CreateBundleResponseDataItemsCardsItems() {
    }

    /**
     * Initialization constructor.
     * @param  pAN  String value for pAN.
     */
    public CreateBundleResponseDataItemsCardsItems(
            String pAN) {
        this.pAN = pAN;
    }

    /**
     * Getter for PAN.
     * Card PAN.
     * @return Returns the String
     */
    @JsonGetter("PAN")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPAN() {
        return pAN;
    }

    /**
     * Setter for PAN.
     * Card PAN.
     * @param pAN Value for String
     */
    @JsonSetter("PAN")
    public void setPAN(String pAN) {
        this.pAN = pAN;
    }

    /**
     * Converts this CreateBundleResponseDataItemsCardsItems into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateBundleResponseDataItemsCardsItems [" + "pAN=" + pAN + "]";
    }

    /**
     * Builds a new {@link CreateBundleResponseDataItemsCardsItems.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateBundleResponseDataItemsCardsItems.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .pAN(getPAN());
        return builder;
    }

    /**
     * Class to build instances of {@link CreateBundleResponseDataItemsCardsItems}.
     */
    public static class Builder {
        private String pAN;



        /**
         * Setter for pAN.
         * @param  pAN  String value for pAN.
         * @return Builder
         */
        public Builder pAN(String pAN) {
            this.pAN = pAN;
            return this;
        }

        /**
         * Builds a new {@link CreateBundleResponseDataItemsCardsItems} object using the set fields.
         * @return {@link CreateBundleResponseDataItemsCardsItems}
         */
        public CreateBundleResponseDataItemsCardsItems build() {
            return new CreateBundleResponseDataItemsCardsItems(pAN);
        }
    }
}
