/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for LocationRestrictions type.
 */
public class LocationRestrictions {
    private LocationRestrictionsCountryRestrictions countryRestrictions;
    private List<LocationRestrictionsNetworkRestrictionsItems> networkRestrictions;
    private List<LocationRestrictionsShellSiteRestrictionsItems> shellSiteRestrictions;
    private List<LocationRestrictionsPartnerSiteRestrictionsItems> partnerSiteRestrictions;

    /**
     * Default constructor.
     */
    public LocationRestrictions() {
    }

    /**
     * Initialization constructor.
     * @param  countryRestrictions  LocationRestrictionsCountryRestrictions value for
     *         countryRestrictions.
     * @param  networkRestrictions  List of LocationRestrictionsNetworkRestrictionsItems value for
     *         networkRestrictions.
     * @param  shellSiteRestrictions  List of LocationRestrictionsShellSiteRestrictionsItems value
     *         for shellSiteRestrictions.
     * @param  partnerSiteRestrictions  List of LocationRestrictionsPartnerSiteRestrictionsItems
     *         value for partnerSiteRestrictions.
     */
    public LocationRestrictions(
            LocationRestrictionsCountryRestrictions countryRestrictions,
            List<LocationRestrictionsNetworkRestrictionsItems> networkRestrictions,
            List<LocationRestrictionsShellSiteRestrictionsItems> shellSiteRestrictions,
            List<LocationRestrictionsPartnerSiteRestrictionsItems> partnerSiteRestrictions) {
        this.countryRestrictions = countryRestrictions;
        this.networkRestrictions = networkRestrictions;
        this.shellSiteRestrictions = shellSiteRestrictions;
        this.partnerSiteRestrictions = partnerSiteRestrictions;
    }

    /**
     * Getter for CountryRestrictions.
     * An entity that encapsulate the country restrictions. Optional.
     * @return Returns the LocationRestrictionsCountryRestrictions
     */
    @JsonGetter("CountryRestrictions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public LocationRestrictionsCountryRestrictions getCountryRestrictions() {
        return countryRestrictions;
    }

    /**
     * Setter for CountryRestrictions.
     * An entity that encapsulate the country restrictions. Optional.
     * @param countryRestrictions Value for LocationRestrictionsCountryRestrictions
     */
    @JsonSetter("CountryRestrictions")
    public void setCountryRestrictions(LocationRestrictionsCountryRestrictions countryRestrictions) {
        this.countryRestrictions = countryRestrictions;
    }

    /**
     * Getter for NetworkRestrictions.
     * A list of NetworkRestriction entity. Each item in the list encapsulates a network restriction
     * in a given country. Optional. The details of the entity are described below:
     * @return Returns the List of LocationRestrictionsNetworkRestrictionsItems
     */
    @JsonGetter("NetworkRestrictions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<LocationRestrictionsNetworkRestrictionsItems> getNetworkRestrictions() {
        return networkRestrictions;
    }

    /**
     * Setter for NetworkRestrictions.
     * A list of NetworkRestriction entity. Each item in the list encapsulates a network restriction
     * in a given country. Optional. The details of the entity are described below:
     * @param networkRestrictions Value for List of LocationRestrictionsNetworkRestrictionsItems
     */
    @JsonSetter("NetworkRestrictions")
    public void setNetworkRestrictions(List<LocationRestrictionsNetworkRestrictionsItems> networkRestrictions) {
        this.networkRestrictions = networkRestrictions;
    }

    /**
     * Getter for ShellSiteRestrictions.
     * A list of ShellSiteRestriction entity. Each item in the list encapsulates a site restriction
     * of Shell network in a given country. Optional. The details of the entity are described below.
     * @return Returns the List of LocationRestrictionsShellSiteRestrictionsItems
     */
    @JsonGetter("ShellSiteRestrictions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<LocationRestrictionsShellSiteRestrictionsItems> getShellSiteRestrictions() {
        return shellSiteRestrictions;
    }

    /**
     * Setter for ShellSiteRestrictions.
     * A list of ShellSiteRestriction entity. Each item in the list encapsulates a site restriction
     * of Shell network in a given country. Optional. The details of the entity are described below.
     * @param shellSiteRestrictions Value for List of LocationRestrictionsShellSiteRestrictionsItems
     */
    @JsonSetter("ShellSiteRestrictions")
    public void setShellSiteRestrictions(List<LocationRestrictionsShellSiteRestrictionsItems> shellSiteRestrictions) {
        this.shellSiteRestrictions = shellSiteRestrictions;
    }

    /**
     * Getter for PartnerSiteRestrictions.
     * A list of PartnerSiteRestriction entity. Each item in the list encapsulates a site
     * restriction of a given partner network. Optional. The details of the entity are described
     * below.
     * @return Returns the List of LocationRestrictionsPartnerSiteRestrictionsItems
     */
    @JsonGetter("PartnerSiteRestrictions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<LocationRestrictionsPartnerSiteRestrictionsItems> getPartnerSiteRestrictions() {
        return partnerSiteRestrictions;
    }

    /**
     * Setter for PartnerSiteRestrictions.
     * A list of PartnerSiteRestriction entity. Each item in the list encapsulates a site
     * restriction of a given partner network. Optional. The details of the entity are described
     * below.
     * @param partnerSiteRestrictions Value for List of LocationRestrictionsPartnerSiteRestrictionsItems
     */
    @JsonSetter("PartnerSiteRestrictions")
    public void setPartnerSiteRestrictions(List<LocationRestrictionsPartnerSiteRestrictionsItems> partnerSiteRestrictions) {
        this.partnerSiteRestrictions = partnerSiteRestrictions;
    }

    /**
     * Converts this LocationRestrictions into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LocationRestrictions [" + "countryRestrictions=" + countryRestrictions
                + ", networkRestrictions=" + networkRestrictions + ", shellSiteRestrictions="
                + shellSiteRestrictions + ", partnerSiteRestrictions=" + partnerSiteRestrictions
                + "]";
    }

    /**
     * Builds a new {@link LocationRestrictions.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LocationRestrictions.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .countryRestrictions(getCountryRestrictions())
                .networkRestrictions(getNetworkRestrictions())
                .shellSiteRestrictions(getShellSiteRestrictions())
                .partnerSiteRestrictions(getPartnerSiteRestrictions());
        return builder;
    }

    /**
     * Class to build instances of {@link LocationRestrictions}.
     */
    public static class Builder {
        private LocationRestrictionsCountryRestrictions countryRestrictions;
        private List<LocationRestrictionsNetworkRestrictionsItems> networkRestrictions;
        private List<LocationRestrictionsShellSiteRestrictionsItems> shellSiteRestrictions;
        private List<LocationRestrictionsPartnerSiteRestrictionsItems> partnerSiteRestrictions;



        /**
         * Setter for countryRestrictions.
         * @param  countryRestrictions  LocationRestrictionsCountryRestrictions value for
         *         countryRestrictions.
         * @return Builder
         */
        public Builder countryRestrictions(
                LocationRestrictionsCountryRestrictions countryRestrictions) {
            this.countryRestrictions = countryRestrictions;
            return this;
        }

        /**
         * Setter for networkRestrictions.
         * @param  networkRestrictions  List of LocationRestrictionsNetworkRestrictionsItems value
         *         for networkRestrictions.
         * @return Builder
         */
        public Builder networkRestrictions(
                List<LocationRestrictionsNetworkRestrictionsItems> networkRestrictions) {
            this.networkRestrictions = networkRestrictions;
            return this;
        }

        /**
         * Setter for shellSiteRestrictions.
         * @param  shellSiteRestrictions  List of LocationRestrictionsShellSiteRestrictionsItems
         *         value for shellSiteRestrictions.
         * @return Builder
         */
        public Builder shellSiteRestrictions(
                List<LocationRestrictionsShellSiteRestrictionsItems> shellSiteRestrictions) {
            this.shellSiteRestrictions = shellSiteRestrictions;
            return this;
        }

        /**
         * Setter for partnerSiteRestrictions.
         * @param  partnerSiteRestrictions  List of LocationRestrictionsPartnerSiteRestrictionsItems
         *         value for partnerSiteRestrictions.
         * @return Builder
         */
        public Builder partnerSiteRestrictions(
                List<LocationRestrictionsPartnerSiteRestrictionsItems> partnerSiteRestrictions) {
            this.partnerSiteRestrictions = partnerSiteRestrictions;
            return this;
        }

        /**
         * Builds a new {@link LocationRestrictions} object using the set fields.
         * @return {@link LocationRestrictions}
         */
        public LocationRestrictions build() {
            return new LocationRestrictions(countryRestrictions, networkRestrictions,
                    shellSiteRestrictions, partnerSiteRestrictions);
        }
    }
}
