/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for PINContact type.
 */
public class PINContact {
    private OptionalNullable<String> deliveryContactTitle;
    private OptionalNullable<String> deliveryContactName;
    private OptionalNullable<String> deliveryCompanyName;
    private OptionalNullable<String> deliveryAddressLine1;
    private OptionalNullable<String> deliveryAddressLine2;
    private OptionalNullable<String> deliveryAddressLine3;
    private OptionalNullable<String> deliveryZipCode;
    private OptionalNullable<String> deliveryCity;
    private OptionalNullable<Integer> deliveryRegionId;
    private OptionalNullable<String> deliveryRegion;
    private OptionalNullable<String> deliveryCountry;
    private OptionalNullable<String> phoneNumber;
    private OptionalNullable<String> emailAddress;
    private Boolean saveForPINReminder;

    /**
     * Default constructor.
     */
    public PINContact() {
    }

    /**
     * Initialization constructor.
     * @param  deliveryContactTitle  String value for deliveryContactTitle.
     * @param  deliveryContactName  String value for deliveryContactName.
     * @param  deliveryCompanyName  String value for deliveryCompanyName.
     * @param  deliveryAddressLine1  String value for deliveryAddressLine1.
     * @param  deliveryAddressLine2  String value for deliveryAddressLine2.
     * @param  deliveryAddressLine3  String value for deliveryAddressLine3.
     * @param  deliveryZipCode  String value for deliveryZipCode.
     * @param  deliveryCity  String value for deliveryCity.
     * @param  deliveryRegionId  Integer value for deliveryRegionId.
     * @param  deliveryRegion  String value for deliveryRegion.
     * @param  deliveryCountry  String value for deliveryCountry.
     * @param  phoneNumber  String value for phoneNumber.
     * @param  emailAddress  String value for emailAddress.
     * @param  saveForPINReminder  Boolean value for saveForPINReminder.
     */
    public PINContact(
            String deliveryContactTitle,
            String deliveryContactName,
            String deliveryCompanyName,
            String deliveryAddressLine1,
            String deliveryAddressLine2,
            String deliveryAddressLine3,
            String deliveryZipCode,
            String deliveryCity,
            Integer deliveryRegionId,
            String deliveryRegion,
            String deliveryCountry,
            String phoneNumber,
            String emailAddress,
            Boolean saveForPINReminder) {
        this.deliveryContactTitle = OptionalNullable.of(deliveryContactTitle);
        this.deliveryContactName = OptionalNullable.of(deliveryContactName);
        this.deliveryCompanyName = OptionalNullable.of(deliveryCompanyName);
        this.deliveryAddressLine1 = OptionalNullable.of(deliveryAddressLine1);
        this.deliveryAddressLine2 = OptionalNullable.of(deliveryAddressLine2);
        this.deliveryAddressLine3 = OptionalNullable.of(deliveryAddressLine3);
        this.deliveryZipCode = OptionalNullable.of(deliveryZipCode);
        this.deliveryCity = OptionalNullable.of(deliveryCity);
        this.deliveryRegionId = OptionalNullable.of(deliveryRegionId);
        this.deliveryRegion = OptionalNullable.of(deliveryRegion);
        this.deliveryCountry = OptionalNullable.of(deliveryCountry);
        this.phoneNumber = OptionalNullable.of(phoneNumber);
        this.emailAddress = OptionalNullable.of(emailAddress);
        this.saveForPINReminder = saveForPINReminder;
    }

    /**
     * Initialization constructor.
     * @param  deliveryContactTitle  String value for deliveryContactTitle.
     * @param  deliveryContactName  String value for deliveryContactName.
     * @param  deliveryCompanyName  String value for deliveryCompanyName.
     * @param  deliveryAddressLine1  String value for deliveryAddressLine1.
     * @param  deliveryAddressLine2  String value for deliveryAddressLine2.
     * @param  deliveryAddressLine3  String value for deliveryAddressLine3.
     * @param  deliveryZipCode  String value for deliveryZipCode.
     * @param  deliveryCity  String value for deliveryCity.
     * @param  deliveryRegionId  Integer value for deliveryRegionId.
     * @param  deliveryRegion  String value for deliveryRegion.
     * @param  deliveryCountry  String value for deliveryCountry.
     * @param  phoneNumber  String value for phoneNumber.
     * @param  emailAddress  String value for emailAddress.
     * @param  saveForPINReminder  Boolean value for saveForPINReminder.
     */

    protected PINContact(OptionalNullable<String> deliveryContactTitle,
            OptionalNullable<String> deliveryContactName,
            OptionalNullable<String> deliveryCompanyName,
            OptionalNullable<String> deliveryAddressLine1,
            OptionalNullable<String> deliveryAddressLine2,
            OptionalNullable<String> deliveryAddressLine3, OptionalNullable<String> deliveryZipCode,
            OptionalNullable<String> deliveryCity, OptionalNullable<Integer> deliveryRegionId,
            OptionalNullable<String> deliveryRegion, OptionalNullable<String> deliveryCountry,
            OptionalNullable<String> phoneNumber, OptionalNullable<String> emailAddress,
            Boolean saveForPINReminder) {
        this.deliveryContactTitle = deliveryContactTitle;
        this.deliveryContactName = deliveryContactName;
        this.deliveryCompanyName = deliveryCompanyName;
        this.deliveryAddressLine1 = deliveryAddressLine1;
        this.deliveryAddressLine2 = deliveryAddressLine2;
        this.deliveryAddressLine3 = deliveryAddressLine3;
        this.deliveryZipCode = deliveryZipCode;
        this.deliveryCity = deliveryCity;
        this.deliveryRegionId = deliveryRegionId;
        this.deliveryRegion = deliveryRegion;
        this.deliveryCountry = deliveryCountry;
        this.phoneNumber = phoneNumber;
        this.emailAddress = emailAddress;
        this.saveForPINReminder = saveForPINReminder;
    }

    /**
     * Internal Getter for DeliveryContactTitle.
     * Title of the contact person &lt;br /&gt; Optional
     * @return Returns the Internal String
     */
    @JsonGetter("DeliveryContactTitle")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDeliveryContactTitle() {
        return this.deliveryContactTitle;
    }

    /**
     * Getter for DeliveryContactTitle.
     * Title of the contact person &lt;br /&gt; Optional
     * @return Returns the String
     */
    public String getDeliveryContactTitle() {
        return OptionalNullable.getFrom(deliveryContactTitle);
    }

    /**
     * Setter for DeliveryContactTitle.
     * Title of the contact person &lt;br /&gt; Optional
     * @param deliveryContactTitle Value for String
     */
    @JsonSetter("DeliveryContactTitle")
    public void setDeliveryContactTitle(String deliveryContactTitle) {
        this.deliveryContactTitle = OptionalNullable.of(deliveryContactTitle);
    }

    /**
     * UnSetter for DeliveryContactTitle.
     * Title of the contact person &lt;br /&gt; Optional
     */
    public void unsetDeliveryContactTitle() {
        deliveryContactTitle = null;
    }

    /**
     * Internal Getter for DeliveryContactName.
     * Name of the contact person &lt;br /&gt; Mandatory - If PINAdviceType is paper else optional. &lt;br /&gt;
     * Max field length: 50 &lt;br /&gt; Optional
     * @return Returns the Internal String
     */
    @JsonGetter("DeliveryContactName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDeliveryContactName() {
        return this.deliveryContactName;
    }

    /**
     * Getter for DeliveryContactName.
     * Name of the contact person &lt;br /&gt; Mandatory - If PINAdviceType is paper else optional. &lt;br /&gt;
     * Max field length: 50 &lt;br /&gt; Optional
     * @return Returns the String
     */
    public String getDeliveryContactName() {
        return OptionalNullable.getFrom(deliveryContactName);
    }

    /**
     * Setter for DeliveryContactName.
     * Name of the contact person &lt;br /&gt; Mandatory - If PINAdviceType is paper else optional. &lt;br /&gt;
     * Max field length: 50 &lt;br /&gt; Optional
     * @param deliveryContactName Value for String
     */
    @JsonSetter("DeliveryContactName")
    public void setDeliveryContactName(String deliveryContactName) {
        this.deliveryContactName = OptionalNullable.of(deliveryContactName);
    }

    /**
     * UnSetter for DeliveryContactName.
     * Name of the contact person &lt;br /&gt; Mandatory - If PINAdviceType is paper else optional. &lt;br /&gt;
     * Max field length: 50 &lt;br /&gt; Optional
     */
    public void unsetDeliveryContactName() {
        deliveryContactName = null;
    }

    /**
     * Internal Getter for DeliveryCompanyName.
     * Company name &lt;br /&gt; Mandatory - If PINAdviceType is paper else optional. &lt;br /&gt; Max field
     * length: 50 &lt;br /&gt; Optional
     * @return Returns the Internal String
     */
    @JsonGetter("DeliveryCompanyName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDeliveryCompanyName() {
        return this.deliveryCompanyName;
    }

    /**
     * Getter for DeliveryCompanyName.
     * Company name &lt;br /&gt; Mandatory - If PINAdviceType is paper else optional. &lt;br /&gt; Max field
     * length: 50 &lt;br /&gt; Optional
     * @return Returns the String
     */
    public String getDeliveryCompanyName() {
        return OptionalNullable.getFrom(deliveryCompanyName);
    }

    /**
     * Setter for DeliveryCompanyName.
     * Company name &lt;br /&gt; Mandatory - If PINAdviceType is paper else optional. &lt;br /&gt; Max field
     * length: 50 &lt;br /&gt; Optional
     * @param deliveryCompanyName Value for String
     */
    @JsonSetter("DeliveryCompanyName")
    public void setDeliveryCompanyName(String deliveryCompanyName) {
        this.deliveryCompanyName = OptionalNullable.of(deliveryCompanyName);
    }

    /**
     * UnSetter for DeliveryCompanyName.
     * Company name &lt;br /&gt; Mandatory - If PINAdviceType is paper else optional. &lt;br /&gt; Max field
     * length: 50 &lt;br /&gt; Optional
     */
    public void unsetDeliveryCompanyName() {
        deliveryCompanyName = null;
    }

    /**
     * Internal Getter for DeliveryAddressLine1.
     * Address line 1 &lt;br /&gt; Mandatory - if PINAdviceType is paper else optional.&lt;br /&gt; Max field
     * length: 40 &lt;br /&gt; Optional
     * @return Returns the Internal String
     */
    @JsonGetter("DeliveryAddressLine1")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDeliveryAddressLine1() {
        return this.deliveryAddressLine1;
    }

    /**
     * Getter for DeliveryAddressLine1.
     * Address line 1 &lt;br /&gt; Mandatory - if PINAdviceType is paper else optional.&lt;br /&gt; Max field
     * length: 40 &lt;br /&gt; Optional
     * @return Returns the String
     */
    public String getDeliveryAddressLine1() {
        return OptionalNullable.getFrom(deliveryAddressLine1);
    }

    /**
     * Setter for DeliveryAddressLine1.
     * Address line 1 &lt;br /&gt; Mandatory - if PINAdviceType is paper else optional.&lt;br /&gt; Max field
     * length: 40 &lt;br /&gt; Optional
     * @param deliveryAddressLine1 Value for String
     */
    @JsonSetter("DeliveryAddressLine1")
    public void setDeliveryAddressLine1(String deliveryAddressLine1) {
        this.deliveryAddressLine1 = OptionalNullable.of(deliveryAddressLine1);
    }

    /**
     * UnSetter for DeliveryAddressLine1.
     * Address line 1 &lt;br /&gt; Mandatory - if PINAdviceType is paper else optional.&lt;br /&gt; Max field
     * length: 40 &lt;br /&gt; Optional
     */
    public void unsetDeliveryAddressLine1() {
        deliveryAddressLine1 = null;
    }

    /**
     * Internal Getter for DeliveryAddressLine2.
     * Address line 2 &lt;br /&gt; Optional &lt;br /&gt; Max field length: 40 &lt;br /&gt; Optional
     * @return Returns the Internal String
     */
    @JsonGetter("DeliveryAddressLine2")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDeliveryAddressLine2() {
        return this.deliveryAddressLine2;
    }

    /**
     * Getter for DeliveryAddressLine2.
     * Address line 2 &lt;br /&gt; Optional &lt;br /&gt; Max field length: 40 &lt;br /&gt; Optional
     * @return Returns the String
     */
    public String getDeliveryAddressLine2() {
        return OptionalNullable.getFrom(deliveryAddressLine2);
    }

    /**
     * Setter for DeliveryAddressLine2.
     * Address line 2 &lt;br /&gt; Optional &lt;br /&gt; Max field length: 40 &lt;br /&gt; Optional
     * @param deliveryAddressLine2 Value for String
     */
    @JsonSetter("DeliveryAddressLine2")
    public void setDeliveryAddressLine2(String deliveryAddressLine2) {
        this.deliveryAddressLine2 = OptionalNullable.of(deliveryAddressLine2);
    }

    /**
     * UnSetter for DeliveryAddressLine2.
     * Address line 2 &lt;br /&gt; Optional &lt;br /&gt; Max field length: 40 &lt;br /&gt; Optional
     */
    public void unsetDeliveryAddressLine2() {
        deliveryAddressLine2 = null;
    }

    /**
     * Internal Getter for DeliveryAddressLine3.
     * Address line 3 &lt;br /&gt; Optional &lt;br /&gt; Max field length: 40 &lt;br /&gt; Optional
     * @return Returns the Internal String
     */
    @JsonGetter("DeliveryAddressLine3")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDeliveryAddressLine3() {
        return this.deliveryAddressLine3;
    }

    /**
     * Getter for DeliveryAddressLine3.
     * Address line 3 &lt;br /&gt; Optional &lt;br /&gt; Max field length: 40 &lt;br /&gt; Optional
     * @return Returns the String
     */
    public String getDeliveryAddressLine3() {
        return OptionalNullable.getFrom(deliveryAddressLine3);
    }

    /**
     * Setter for DeliveryAddressLine3.
     * Address line 3 &lt;br /&gt; Optional &lt;br /&gt; Max field length: 40 &lt;br /&gt; Optional
     * @param deliveryAddressLine3 Value for String
     */
    @JsonSetter("DeliveryAddressLine3")
    public void setDeliveryAddressLine3(String deliveryAddressLine3) {
        this.deliveryAddressLine3 = OptionalNullable.of(deliveryAddressLine3);
    }

    /**
     * UnSetter for DeliveryAddressLine3.
     * Address line 3 &lt;br /&gt; Optional &lt;br /&gt; Max field length: 40 &lt;br /&gt; Optional
     */
    public void unsetDeliveryAddressLine3() {
        deliveryAddressLine3 = null;
    }

    /**
     * Internal Getter for DeliveryZipCode.
     * ZIP code &lt;br /&gt; Mandatory - if PINAdviceType is paper else optional. &lt;br /&gt; Max field length:
     * 10 &lt;br /&gt; Optional
     * @return Returns the Internal String
     */
    @JsonGetter("DeliveryZipCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDeliveryZipCode() {
        return this.deliveryZipCode;
    }

    /**
     * Getter for DeliveryZipCode.
     * ZIP code &lt;br /&gt; Mandatory - if PINAdviceType is paper else optional. &lt;br /&gt; Max field length:
     * 10 &lt;br /&gt; Optional
     * @return Returns the String
     */
    public String getDeliveryZipCode() {
        return OptionalNullable.getFrom(deliveryZipCode);
    }

    /**
     * Setter for DeliveryZipCode.
     * ZIP code &lt;br /&gt; Mandatory - if PINAdviceType is paper else optional. &lt;br /&gt; Max field length:
     * 10 &lt;br /&gt; Optional
     * @param deliveryZipCode Value for String
     */
    @JsonSetter("DeliveryZipCode")
    public void setDeliveryZipCode(String deliveryZipCode) {
        this.deliveryZipCode = OptionalNullable.of(deliveryZipCode);
    }

    /**
     * UnSetter for DeliveryZipCode.
     * ZIP code &lt;br /&gt; Mandatory - if PINAdviceType is paper else optional. &lt;br /&gt; Max field length:
     * 10 &lt;br /&gt; Optional
     */
    public void unsetDeliveryZipCode() {
        deliveryZipCode = null;
    }

    /**
     * Internal Getter for DeliveryCity.
     * City &lt;br /&gt; Mandatory - If PINAdviceType is paper else optional. &lt;br /&gt; Max field length: 40
     * &lt;br /&gt; Optional
     * @return Returns the Internal String
     */
    @JsonGetter("DeliveryCity")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDeliveryCity() {
        return this.deliveryCity;
    }

    /**
     * Getter for DeliveryCity.
     * City &lt;br /&gt; Mandatory - If PINAdviceType is paper else optional. &lt;br /&gt; Max field length: 40
     * &lt;br /&gt; Optional
     * @return Returns the String
     */
    public String getDeliveryCity() {
        return OptionalNullable.getFrom(deliveryCity);
    }

    /**
     * Setter for DeliveryCity.
     * City &lt;br /&gt; Mandatory - If PINAdviceType is paper else optional. &lt;br /&gt; Max field length: 40
     * &lt;br /&gt; Optional
     * @param deliveryCity Value for String
     */
    @JsonSetter("DeliveryCity")
    public void setDeliveryCity(String deliveryCity) {
        this.deliveryCity = OptionalNullable.of(deliveryCity);
    }

    /**
     * UnSetter for DeliveryCity.
     * City &lt;br /&gt; Mandatory - If PINAdviceType is paper else optional. &lt;br /&gt; Max field length: 40
     * &lt;br /&gt; Optional
     */
    public void unsetDeliveryCity() {
        deliveryCity = null;
    }

    /**
     * Internal Getter for DeliveryRegionId.
     * Region Id &lt;br /&gt; Optional
     * @return Returns the Internal Integer
     */
    @JsonGetter("DeliveryRegionId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetDeliveryRegionId() {
        return this.deliveryRegionId;
    }

    /**
     * Getter for DeliveryRegionId.
     * Region Id &lt;br /&gt; Optional
     * @return Returns the Integer
     */
    public Integer getDeliveryRegionId() {
        return OptionalNullable.getFrom(deliveryRegionId);
    }

    /**
     * Setter for DeliveryRegionId.
     * Region Id &lt;br /&gt; Optional
     * @param deliveryRegionId Value for Integer
     */
    @JsonSetter("DeliveryRegionId")
    public void setDeliveryRegionId(Integer deliveryRegionId) {
        this.deliveryRegionId = OptionalNullable.of(deliveryRegionId);
    }

    /**
     * UnSetter for DeliveryRegionId.
     * Region Id &lt;br /&gt; Optional
     */
    public void unsetDeliveryRegionId() {
        deliveryRegionId = null;
    }

    /**
     * Internal Getter for DeliveryRegion.
     * Region &lt;br /&gt; Optional&lt;br /&gt;
     * @return Returns the Internal String
     */
    @JsonGetter("DeliveryRegion")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDeliveryRegion() {
        return this.deliveryRegion;
    }

    /**
     * Getter for DeliveryRegion.
     * Region &lt;br /&gt; Optional&lt;br /&gt;
     * @return Returns the String
     */
    public String getDeliveryRegion() {
        return OptionalNullable.getFrom(deliveryRegion);
    }

    /**
     * Setter for DeliveryRegion.
     * Region &lt;br /&gt; Optional&lt;br /&gt;
     * @param deliveryRegion Value for String
     */
    @JsonSetter("DeliveryRegion")
    public void setDeliveryRegion(String deliveryRegion) {
        this.deliveryRegion = OptionalNullable.of(deliveryRegion);
    }

    /**
     * UnSetter for DeliveryRegion.
     * Region &lt;br /&gt; Optional&lt;br /&gt;
     */
    public void unsetDeliveryRegion() {
        deliveryRegion = null;
    }

    /**
     * Internal Getter for DeliveryCountry.
     * The ISO code of the country.&lt;br /&gt; Mandatory if PINAdviceType is paper else optional.
     * @return Returns the Internal String
     */
    @JsonGetter("DeliveryCountry")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDeliveryCountry() {
        return this.deliveryCountry;
    }

    /**
     * Getter for DeliveryCountry.
     * The ISO code of the country.&lt;br /&gt; Mandatory if PINAdviceType is paper else optional.
     * @return Returns the String
     */
    public String getDeliveryCountry() {
        return OptionalNullable.getFrom(deliveryCountry);
    }

    /**
     * Setter for DeliveryCountry.
     * The ISO code of the country.&lt;br /&gt; Mandatory if PINAdviceType is paper else optional.
     * @param deliveryCountry Value for String
     */
    @JsonSetter("DeliveryCountry")
    public void setDeliveryCountry(String deliveryCountry) {
        this.deliveryCountry = OptionalNullable.of(deliveryCountry);
    }

    /**
     * UnSetter for DeliveryCountry.
     * The ISO code of the country.&lt;br /&gt; Mandatory if PINAdviceType is paper else optional.
     */
    public void unsetDeliveryCountry() {
        deliveryCountry = null;
    }

    /**
     * Internal Getter for PhoneNumber.
     * Phone number for to send SMS of the PIN in case PINAdviceType is SMS.&lt;br /&gt; Mandatory if
     * PINAdviceType is SMS else optional.&lt;br /&gt; Max field length: 20
     * @return Returns the Internal String
     */
    @JsonGetter("PhoneNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetPhoneNumber() {
        return this.phoneNumber;
    }

    /**
     * Getter for PhoneNumber.
     * Phone number for to send SMS of the PIN in case PINAdviceType is SMS.&lt;br /&gt; Mandatory if
     * PINAdviceType is SMS else optional.&lt;br /&gt; Max field length: 20
     * @return Returns the String
     */
    public String getPhoneNumber() {
        return OptionalNullable.getFrom(phoneNumber);
    }

    /**
     * Setter for PhoneNumber.
     * Phone number for to send SMS of the PIN in case PINAdviceType is SMS.&lt;br /&gt; Mandatory if
     * PINAdviceType is SMS else optional.&lt;br /&gt; Max field length: 20
     * @param phoneNumber Value for String
     */
    @JsonSetter("PhoneNumber")
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = OptionalNullable.of(phoneNumber);
    }

    /**
     * UnSetter for PhoneNumber.
     * Phone number for to send SMS of the PIN in case PINAdviceType is SMS.&lt;br /&gt; Mandatory if
     * PINAdviceType is SMS else optional.&lt;br /&gt; Max field length: 20
     */
    public void unsetPhoneNumber() {
        phoneNumber = null;
    }

    /**
     * Internal Getter for EmailAddress.
     * Email address for to send email of the PIN in case PINAdviceType is Email.&lt;br /&gt; Mandatory if
     * PINAdviceType is email else optional.&lt;br /&gt; Max field length: 90. &lt;br/&gt;Note:Based on the
     * international standard that there can be Max Length 64 before the {@literal @} (the 'Local part’)
     * =64(minimum of 1) Max Lenth after the (the domain) = 88 (Minimum of 2)
     * @return Returns the Internal String
     */
    @JsonGetter("EmailAddress")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetEmailAddress() {
        return this.emailAddress;
    }

    /**
     * Getter for EmailAddress.
     * Email address for to send email of the PIN in case PINAdviceType is Email.&lt;br /&gt; Mandatory if
     * PINAdviceType is email else optional.&lt;br /&gt; Max field length: 90. &lt;br/&gt;Note:Based on the
     * international standard that there can be Max Length 64 before the {@literal @} (the 'Local part’)
     * =64(minimum of 1) Max Lenth after the (the domain) = 88 (Minimum of 2)
     * @return Returns the String
     */
    public String getEmailAddress() {
        return OptionalNullable.getFrom(emailAddress);
    }

    /**
     * Setter for EmailAddress.
     * Email address for to send email of the PIN in case PINAdviceType is Email.&lt;br /&gt; Mandatory if
     * PINAdviceType is email else optional.&lt;br /&gt; Max field length: 90. &lt;br/&gt;Note:Based on the
     * international standard that there can be Max Length 64 before the {@literal @} (the 'Local part’)
     * =64(minimum of 1) Max Lenth after the (the domain) = 88 (Minimum of 2)
     * @param emailAddress Value for String
     */
    @JsonSetter("EmailAddress")
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = OptionalNullable.of(emailAddress);
    }

    /**
     * UnSetter for EmailAddress.
     * Email address for to send email of the PIN in case PINAdviceType is Email.&lt;br /&gt; Mandatory if
     * PINAdviceType is email else optional.&lt;br /&gt; Max field length: 90. &lt;br/&gt;Note:Based on the
     * international standard that there can be Max Length 64 before the {@literal @} (the 'Local part’)
     * =64(minimum of 1) Max Lenth after the (the domain) = 88 (Minimum of 2)
     */
    public void unsetEmailAddress() {
        emailAddress = null;
    }

    /**
     * Getter for SaveForPINReminder.
     * The given address will be used for sending PIN reminders in future when requested.&lt;br /&gt; Only
     * allowed for paper delivery&lt;br /&gt; Optional
     * @return Returns the Boolean
     */
    @JsonGetter("SaveForPINReminder")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getSaveForPINReminder() {
        return saveForPINReminder;
    }

    /**
     * Setter for SaveForPINReminder.
     * The given address will be used for sending PIN reminders in future when requested.&lt;br /&gt; Only
     * allowed for paper delivery&lt;br /&gt; Optional
     * @param saveForPINReminder Value for Boolean
     */
    @JsonSetter("SaveForPINReminder")
    public void setSaveForPINReminder(Boolean saveForPINReminder) {
        this.saveForPINReminder = saveForPINReminder;
    }

    /**
     * Converts this PINContact into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PINContact [" + "deliveryContactTitle=" + deliveryContactTitle
                + ", deliveryContactName=" + deliveryContactName + ", deliveryCompanyName="
                + deliveryCompanyName + ", deliveryAddressLine1=" + deliveryAddressLine1
                + ", deliveryAddressLine2=" + deliveryAddressLine2 + ", deliveryAddressLine3="
                + deliveryAddressLine3 + ", deliveryZipCode=" + deliveryZipCode + ", deliveryCity="
                + deliveryCity + ", deliveryRegionId=" + deliveryRegionId + ", deliveryRegion="
                + deliveryRegion + ", deliveryCountry=" + deliveryCountry + ", phoneNumber="
                + phoneNumber + ", emailAddress=" + emailAddress + ", saveForPINReminder="
                + saveForPINReminder + "]";
    }

    /**
     * Builds a new {@link PINContact.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PINContact.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .saveForPINReminder(getSaveForPINReminder());
        builder.deliveryContactTitle = internalGetDeliveryContactTitle();
        builder.deliveryContactName = internalGetDeliveryContactName();
        builder.deliveryCompanyName = internalGetDeliveryCompanyName();
        builder.deliveryAddressLine1 = internalGetDeliveryAddressLine1();
        builder.deliveryAddressLine2 = internalGetDeliveryAddressLine2();
        builder.deliveryAddressLine3 = internalGetDeliveryAddressLine3();
        builder.deliveryZipCode = internalGetDeliveryZipCode();
        builder.deliveryCity = internalGetDeliveryCity();
        builder.deliveryRegionId = internalGetDeliveryRegionId();
        builder.deliveryRegion = internalGetDeliveryRegion();
        builder.deliveryCountry = internalGetDeliveryCountry();
        builder.phoneNumber = internalGetPhoneNumber();
        builder.emailAddress = internalGetEmailAddress();
        return builder;
    }

    /**
     * Class to build instances of {@link PINContact}.
     */
    public static class Builder {
        private OptionalNullable<String> deliveryContactTitle;
        private OptionalNullable<String> deliveryContactName;
        private OptionalNullable<String> deliveryCompanyName;
        private OptionalNullable<String> deliveryAddressLine1;
        private OptionalNullable<String> deliveryAddressLine2;
        private OptionalNullable<String> deliveryAddressLine3;
        private OptionalNullable<String> deliveryZipCode;
        private OptionalNullable<String> deliveryCity;
        private OptionalNullable<Integer> deliveryRegionId;
        private OptionalNullable<String> deliveryRegion;
        private OptionalNullable<String> deliveryCountry;
        private OptionalNullable<String> phoneNumber;
        private OptionalNullable<String> emailAddress;
        private Boolean saveForPINReminder;



        /**
         * Setter for deliveryContactTitle.
         * @param  deliveryContactTitle  String value for deliveryContactTitle.
         * @return Builder
         */
        public Builder deliveryContactTitle(String deliveryContactTitle) {
            this.deliveryContactTitle = OptionalNullable.of(deliveryContactTitle);
            return this;
        }

        /**
         * UnSetter for deliveryContactTitle.
         * @return Builder
         */
        public Builder unsetDeliveryContactTitle() {
            deliveryContactTitle = null;
            return this;
        }

        /**
         * Setter for deliveryContactName.
         * @param  deliveryContactName  String value for deliveryContactName.
         * @return Builder
         */
        public Builder deliveryContactName(String deliveryContactName) {
            this.deliveryContactName = OptionalNullable.of(deliveryContactName);
            return this;
        }

        /**
         * UnSetter for deliveryContactName.
         * @return Builder
         */
        public Builder unsetDeliveryContactName() {
            deliveryContactName = null;
            return this;
        }

        /**
         * Setter for deliveryCompanyName.
         * @param  deliveryCompanyName  String value for deliveryCompanyName.
         * @return Builder
         */
        public Builder deliveryCompanyName(String deliveryCompanyName) {
            this.deliveryCompanyName = OptionalNullable.of(deliveryCompanyName);
            return this;
        }

        /**
         * UnSetter for deliveryCompanyName.
         * @return Builder
         */
        public Builder unsetDeliveryCompanyName() {
            deliveryCompanyName = null;
            return this;
        }

        /**
         * Setter for deliveryAddressLine1.
         * @param  deliveryAddressLine1  String value for deliveryAddressLine1.
         * @return Builder
         */
        public Builder deliveryAddressLine1(String deliveryAddressLine1) {
            this.deliveryAddressLine1 = OptionalNullable.of(deliveryAddressLine1);
            return this;
        }

        /**
         * UnSetter for deliveryAddressLine1.
         * @return Builder
         */
        public Builder unsetDeliveryAddressLine1() {
            deliveryAddressLine1 = null;
            return this;
        }

        /**
         * Setter for deliveryAddressLine2.
         * @param  deliveryAddressLine2  String value for deliveryAddressLine2.
         * @return Builder
         */
        public Builder deliveryAddressLine2(String deliveryAddressLine2) {
            this.deliveryAddressLine2 = OptionalNullable.of(deliveryAddressLine2);
            return this;
        }

        /**
         * UnSetter for deliveryAddressLine2.
         * @return Builder
         */
        public Builder unsetDeliveryAddressLine2() {
            deliveryAddressLine2 = null;
            return this;
        }

        /**
         * Setter for deliveryAddressLine3.
         * @param  deliveryAddressLine3  String value for deliveryAddressLine3.
         * @return Builder
         */
        public Builder deliveryAddressLine3(String deliveryAddressLine3) {
            this.deliveryAddressLine3 = OptionalNullable.of(deliveryAddressLine3);
            return this;
        }

        /**
         * UnSetter for deliveryAddressLine3.
         * @return Builder
         */
        public Builder unsetDeliveryAddressLine3() {
            deliveryAddressLine3 = null;
            return this;
        }

        /**
         * Setter for deliveryZipCode.
         * @param  deliveryZipCode  String value for deliveryZipCode.
         * @return Builder
         */
        public Builder deliveryZipCode(String deliveryZipCode) {
            this.deliveryZipCode = OptionalNullable.of(deliveryZipCode);
            return this;
        }

        /**
         * UnSetter for deliveryZipCode.
         * @return Builder
         */
        public Builder unsetDeliveryZipCode() {
            deliveryZipCode = null;
            return this;
        }

        /**
         * Setter for deliveryCity.
         * @param  deliveryCity  String value for deliveryCity.
         * @return Builder
         */
        public Builder deliveryCity(String deliveryCity) {
            this.deliveryCity = OptionalNullable.of(deliveryCity);
            return this;
        }

        /**
         * UnSetter for deliveryCity.
         * @return Builder
         */
        public Builder unsetDeliveryCity() {
            deliveryCity = null;
            return this;
        }

        /**
         * Setter for deliveryRegionId.
         * @param  deliveryRegionId  Integer value for deliveryRegionId.
         * @return Builder
         */
        public Builder deliveryRegionId(Integer deliveryRegionId) {
            this.deliveryRegionId = OptionalNullable.of(deliveryRegionId);
            return this;
        }

        /**
         * UnSetter for deliveryRegionId.
         * @return Builder
         */
        public Builder unsetDeliveryRegionId() {
            deliveryRegionId = null;
            return this;
        }

        /**
         * Setter for deliveryRegion.
         * @param  deliveryRegion  String value for deliveryRegion.
         * @return Builder
         */
        public Builder deliveryRegion(String deliveryRegion) {
            this.deliveryRegion = OptionalNullable.of(deliveryRegion);
            return this;
        }

        /**
         * UnSetter for deliveryRegion.
         * @return Builder
         */
        public Builder unsetDeliveryRegion() {
            deliveryRegion = null;
            return this;
        }

        /**
         * Setter for deliveryCountry.
         * @param  deliveryCountry  String value for deliveryCountry.
         * @return Builder
         */
        public Builder deliveryCountry(String deliveryCountry) {
            this.deliveryCountry = OptionalNullable.of(deliveryCountry);
            return this;
        }

        /**
         * UnSetter for deliveryCountry.
         * @return Builder
         */
        public Builder unsetDeliveryCountry() {
            deliveryCountry = null;
            return this;
        }

        /**
         * Setter for phoneNumber.
         * @param  phoneNumber  String value for phoneNumber.
         * @return Builder
         */
        public Builder phoneNumber(String phoneNumber) {
            this.phoneNumber = OptionalNullable.of(phoneNumber);
            return this;
        }

        /**
         * UnSetter for phoneNumber.
         * @return Builder
         */
        public Builder unsetPhoneNumber() {
            phoneNumber = null;
            return this;
        }

        /**
         * Setter for emailAddress.
         * @param  emailAddress  String value for emailAddress.
         * @return Builder
         */
        public Builder emailAddress(String emailAddress) {
            this.emailAddress = OptionalNullable.of(emailAddress);
            return this;
        }

        /**
         * UnSetter for emailAddress.
         * @return Builder
         */
        public Builder unsetEmailAddress() {
            emailAddress = null;
            return this;
        }

        /**
         * Setter for saveForPINReminder.
         * @param  saveForPINReminder  Boolean value for saveForPINReminder.
         * @return Builder
         */
        public Builder saveForPINReminder(Boolean saveForPINReminder) {
            this.saveForPINReminder = saveForPINReminder;
            return this;
        }

        /**
         * Builds a new {@link PINContact} object using the set fields.
         * @return {@link PINContact}
         */
        public PINContact build() {
            return new PINContact(deliveryContactTitle, deliveryContactName, deliveryCompanyName,
                    deliveryAddressLine1, deliveryAddressLine2, deliveryAddressLine3,
                    deliveryZipCode, deliveryCity, deliveryRegionId, deliveryRegion,
                    deliveryCountry, phoneNumber, emailAddress, saveForPINReminder);
        }
    }
}
