/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.shell.apitest.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RestrictioncardsRes type.
 */
public class RestrictioncardsRes {
    private Integer accountId;
    private String accountNumber;
    private String cardId;
    private String pAN;
    private String usageRestrictionStatus;
    private String usageRestrictionDescription;
    private String dayTimeRestrictionStatus;
    private String dayTimeRestrictionDescription;
    private String productRestrictionStatus;
    private String productRestrictionDescription;
    private String locationRestrictionStatus;
    private String locationRestrictionStatusDescription;
    private String validationErrorCode;
    private String validationErrorDescription;

    /**
     * Default constructor.
     */
    public RestrictioncardsRes() {
    }

    /**
     * Initialization constructor.
     * @param  accountId  Integer value for accountId.
     * @param  accountNumber  String value for accountNumber.
     * @param  cardId  String value for cardId.
     * @param  pAN  String value for pAN.
     * @param  usageRestrictionStatus  String value for usageRestrictionStatus.
     * @param  usageRestrictionDescription  String value for usageRestrictionDescription.
     * @param  dayTimeRestrictionStatus  String value for dayTimeRestrictionStatus.
     * @param  dayTimeRestrictionDescription  String value for dayTimeRestrictionDescription.
     * @param  productRestrictionStatus  String value for productRestrictionStatus.
     * @param  productRestrictionDescription  String value for productRestrictionDescription.
     * @param  locationRestrictionStatus  String value for locationRestrictionStatus.
     * @param  locationRestrictionStatusDescription  String value for
     *         locationRestrictionStatusDescription.
     * @param  validationErrorCode  String value for validationErrorCode.
     * @param  validationErrorDescription  String value for validationErrorDescription.
     */
    public RestrictioncardsRes(
            Integer accountId,
            String accountNumber,
            String cardId,
            String pAN,
            String usageRestrictionStatus,
            String usageRestrictionDescription,
            String dayTimeRestrictionStatus,
            String dayTimeRestrictionDescription,
            String productRestrictionStatus,
            String productRestrictionDescription,
            String locationRestrictionStatus,
            String locationRestrictionStatusDescription,
            String validationErrorCode,
            String validationErrorDescription) {
        this.accountId = accountId;
        this.accountNumber = accountNumber;
        this.cardId = cardId;
        this.pAN = pAN;
        this.usageRestrictionStatus = usageRestrictionStatus;
        this.usageRestrictionDescription = usageRestrictionDescription;
        this.dayTimeRestrictionStatus = dayTimeRestrictionStatus;
        this.dayTimeRestrictionDescription = dayTimeRestrictionDescription;
        this.productRestrictionStatus = productRestrictionStatus;
        this.productRestrictionDescription = productRestrictionDescription;
        this.locationRestrictionStatus = locationRestrictionStatus;
        this.locationRestrictionStatusDescription = locationRestrictionStatusDescription;
        this.validationErrorCode = validationErrorCode;
        this.validationErrorDescription = validationErrorDescription;
    }

    /**
     * Getter for AccountId.
     * Account Id of the customer. Example: 123456
     * @return Returns the Integer
     */
    @JsonGetter("AccountId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * Setter for AccountId.
     * Account Id of the customer. Example: 123456
     * @param accountId Value for Integer
     */
    @JsonSetter("AccountId")
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for AccountNumber.
     * Account Number of the customer. Example: GB000000123
     * @return Returns the String
     */
    @JsonGetter("AccountNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Setter for AccountNumber.
     * Account Number of the customer. Example: GB000000123
     * @param accountNumber Value for String
     */
    @JsonSetter("AccountNumber")
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Getter for CardId.
     * Unique Card Id Example: 275549
     * @return Returns the String
     */
    @JsonGetter("CardId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardId() {
        return cardId;
    }

    /**
     * Setter for CardId.
     * Unique Card Id Example: 275549
     * @param cardId Value for String
     */
    @JsonSetter("CardId")
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    /**
     * Getter for PAN.
     * Card PAN. Example: 7002051006629890645
     * @return Returns the String
     */
    @JsonGetter("PAN")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPAN() {
        return pAN;
    }

    /**
     * Setter for PAN.
     * Card PAN. Example: 7002051006629890645
     * @param pAN Value for String
     */
    @JsonSetter("PAN")
    public void setPAN(String pAN) {
        this.pAN = pAN;
    }

    /**
     * Getter for UsageRestrictionStatus.
     * Status of the card usage restriction submitted. Based on the response the value will be set
     * as either “Success” or “Failed”.
     * @return Returns the String
     */
    @JsonGetter("UsageRestrictionStatus")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUsageRestrictionStatus() {
        return usageRestrictionStatus;
    }

    /**
     * Setter for UsageRestrictionStatus.
     * Status of the card usage restriction submitted. Based on the response the value will be set
     * as either “Success” or “Failed”.
     * @param usageRestrictionStatus Value for String
     */
    @JsonSetter("UsageRestrictionStatus")
    public void setUsageRestrictionStatus(String usageRestrictionStatus) {
        this.usageRestrictionStatus = usageRestrictionStatus;
    }

    /**
     * Getter for UsageRestrictionDescription.
     * Response for the usage restriction in case of an error. This field will have a value only
     * when “UsageRestrictionStatus” is “Failed”.
     * @return Returns the String
     */
    @JsonGetter("UsageRestrictionDescription")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUsageRestrictionDescription() {
        return usageRestrictionDescription;
    }

    /**
     * Setter for UsageRestrictionDescription.
     * Response for the usage restriction in case of an error. This field will have a value only
     * when “UsageRestrictionStatus” is “Failed”.
     * @param usageRestrictionDescription Value for String
     */
    @JsonSetter("UsageRestrictionDescription")
    public void setUsageRestrictionDescription(String usageRestrictionDescription) {
        this.usageRestrictionDescription = usageRestrictionDescription;
    }

    /**
     * Getter for DayTimeRestrictionStatus.
     * Status of the card day/time restriction submitted. Based on the response from Gateway value
     * will be set as either “Success” or “Failed”.
     * @return Returns the String
     */
    @JsonGetter("DayTimeRestrictionStatus")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDayTimeRestrictionStatus() {
        return dayTimeRestrictionStatus;
    }

    /**
     * Setter for DayTimeRestrictionStatus.
     * Status of the card day/time restriction submitted. Based on the response from Gateway value
     * will be set as either “Success” or “Failed”.
     * @param dayTimeRestrictionStatus Value for String
     */
    @JsonSetter("DayTimeRestrictionStatus")
    public void setDayTimeRestrictionStatus(String dayTimeRestrictionStatus) {
        this.dayTimeRestrictionStatus = dayTimeRestrictionStatus;
    }

    /**
     * Getter for DayTimeRestrictionDescription.
     * Response for the day/time restriction in case of an error. This field will have a value only
     * when “DayTimeRestrictionStatus” is “Failed”.
     * @return Returns the String
     */
    @JsonGetter("DayTimeRestrictionDescription")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDayTimeRestrictionDescription() {
        return dayTimeRestrictionDescription;
    }

    /**
     * Setter for DayTimeRestrictionDescription.
     * Response for the day/time restriction in case of an error. This field will have a value only
     * when “DayTimeRestrictionStatus” is “Failed”.
     * @param dayTimeRestrictionDescription Value for String
     */
    @JsonSetter("DayTimeRestrictionDescription")
    public void setDayTimeRestrictionDescription(String dayTimeRestrictionDescription) {
        this.dayTimeRestrictionDescription = dayTimeRestrictionDescription;
    }

    /**
     * Getter for ProductRestrictionStatus.
     * Status of the card product restriction submitted. Based on the response the value will be set
     * either as “Success” or “Failed”.
     * @return Returns the String
     */
    @JsonGetter("ProductRestrictionStatus")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getProductRestrictionStatus() {
        return productRestrictionStatus;
    }

    /**
     * Setter for ProductRestrictionStatus.
     * Status of the card product restriction submitted. Based on the response the value will be set
     * either as “Success” or “Failed”.
     * @param productRestrictionStatus Value for String
     */
    @JsonSetter("ProductRestrictionStatus")
    public void setProductRestrictionStatus(String productRestrictionStatus) {
        this.productRestrictionStatus = productRestrictionStatus;
    }

    /**
     * Getter for ProductRestrictionDescription.
     * Response for the product restriction in case of an error. This field will have a value only
     * when “ProductRestrictionStatus” is “Failed”.
     * @return Returns the String
     */
    @JsonGetter("ProductRestrictionDescription")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getProductRestrictionDescription() {
        return productRestrictionDescription;
    }

    /**
     * Setter for ProductRestrictionDescription.
     * Response for the product restriction in case of an error. This field will have a value only
     * when “ProductRestrictionStatus” is “Failed”.
     * @param productRestrictionDescription Value for String
     */
    @JsonSetter("ProductRestrictionDescription")
    public void setProductRestrictionDescription(String productRestrictionDescription) {
        this.productRestrictionDescription = productRestrictionDescription;
    }

    /**
     * Getter for LocationRestrictionStatus.
     * Card Location restriction submitted, based on response value set as “Success” or “Failed”.
     * @return Returns the String
     */
    @JsonGetter("LocationRestrictionStatus")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLocationRestrictionStatus() {
        return locationRestrictionStatus;
    }

    /**
     * Setter for LocationRestrictionStatus.
     * Card Location restriction submitted, based on response value set as “Success” or “Failed”.
     * @param locationRestrictionStatus Value for String
     */
    @JsonSetter("LocationRestrictionStatus")
    public void setLocationRestrictionStatus(String locationRestrictionStatus) {
        this.locationRestrictionStatus = locationRestrictionStatus;
    }

    /**
     * Getter for LocationRestrictionStatusDescription.
     * Response for the location restriction in case of an error. This field will have a value only
     * when “LocationRestrictionStatus” is “Failed”.
     * @return Returns the String
     */
    @JsonGetter("LocationRestrictionStatusDescription")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLocationRestrictionStatusDescription() {
        return locationRestrictionStatusDescription;
    }

    /**
     * Setter for LocationRestrictionStatusDescription.
     * Response for the location restriction in case of an error. This field will have a value only
     * when “LocationRestrictionStatus” is “Failed”.
     * @param locationRestrictionStatusDescription Value for String
     */
    @JsonSetter("LocationRestrictionStatusDescription")
    public void setLocationRestrictionStatusDescription(String locationRestrictionStatusDescription) {
        this.locationRestrictionStatusDescription = locationRestrictionStatusDescription;
    }

    /**
     * Getter for ValidationErrorCode.
     * Error code for validation failure.
     * @return Returns the String
     */
    @JsonGetter("ValidationErrorCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getValidationErrorCode() {
        return validationErrorCode;
    }

    /**
     * Setter for ValidationErrorCode.
     * Error code for validation failure.
     * @param validationErrorCode Value for String
     */
    @JsonSetter("ValidationErrorCode")
    public void setValidationErrorCode(String validationErrorCode) {
        this.validationErrorCode = validationErrorCode;
    }

    /**
     * Getter for ValidationErrorDescription.
     * Description of validation failure.
     * @return Returns the String
     */
    @JsonGetter("ValidationErrorDescription")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getValidationErrorDescription() {
        return validationErrorDescription;
    }

    /**
     * Setter for ValidationErrorDescription.
     * Description of validation failure.
     * @param validationErrorDescription Value for String
     */
    @JsonSetter("ValidationErrorDescription")
    public void setValidationErrorDescription(String validationErrorDescription) {
        this.validationErrorDescription = validationErrorDescription;
    }

    /**
     * Converts this RestrictioncardsRes into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RestrictioncardsRes [" + "accountId=" + accountId + ", accountNumber="
                + accountNumber + ", cardId=" + cardId + ", pAN=" + pAN
                + ", usageRestrictionStatus=" + usageRestrictionStatus
                + ", usageRestrictionDescription=" + usageRestrictionDescription
                + ", dayTimeRestrictionStatus=" + dayTimeRestrictionStatus
                + ", dayTimeRestrictionDescription=" + dayTimeRestrictionDescription
                + ", productRestrictionStatus=" + productRestrictionStatus
                + ", productRestrictionDescription=" + productRestrictionDescription
                + ", locationRestrictionStatus=" + locationRestrictionStatus
                + ", locationRestrictionStatusDescription=" + locationRestrictionStatusDescription
                + ", validationErrorCode=" + validationErrorCode + ", validationErrorDescription="
                + validationErrorDescription + "]";
    }

    /**
     * Builds a new {@link RestrictioncardsRes.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RestrictioncardsRes.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accountId(getAccountId())
                .accountNumber(getAccountNumber())
                .cardId(getCardId())
                .pAN(getPAN())
                .usageRestrictionStatus(getUsageRestrictionStatus())
                .usageRestrictionDescription(getUsageRestrictionDescription())
                .dayTimeRestrictionStatus(getDayTimeRestrictionStatus())
                .dayTimeRestrictionDescription(getDayTimeRestrictionDescription())
                .productRestrictionStatus(getProductRestrictionStatus())
                .productRestrictionDescription(getProductRestrictionDescription())
                .locationRestrictionStatus(getLocationRestrictionStatus())
                .locationRestrictionStatusDescription(getLocationRestrictionStatusDescription())
                .validationErrorCode(getValidationErrorCode())
                .validationErrorDescription(getValidationErrorDescription());
        return builder;
    }

    /**
     * Class to build instances of {@link RestrictioncardsRes}.
     */
    public static class Builder {
        private Integer accountId;
        private String accountNumber;
        private String cardId;
        private String pAN;
        private String usageRestrictionStatus;
        private String usageRestrictionDescription;
        private String dayTimeRestrictionStatus;
        private String dayTimeRestrictionDescription;
        private String productRestrictionStatus;
        private String productRestrictionDescription;
        private String locationRestrictionStatus;
        private String locationRestrictionStatusDescription;
        private String validationErrorCode;
        private String validationErrorDescription;



        /**
         * Setter for accountId.
         * @param  accountId  Integer value for accountId.
         * @return Builder
         */
        public Builder accountId(Integer accountId) {
            this.accountId = accountId;
            return this;
        }

        /**
         * Setter for accountNumber.
         * @param  accountNumber  String value for accountNumber.
         * @return Builder
         */
        public Builder accountNumber(String accountNumber) {
            this.accountNumber = accountNumber;
            return this;
        }

        /**
         * Setter for cardId.
         * @param  cardId  String value for cardId.
         * @return Builder
         */
        public Builder cardId(String cardId) {
            this.cardId = cardId;
            return this;
        }

        /**
         * Setter for pAN.
         * @param  pAN  String value for pAN.
         * @return Builder
         */
        public Builder pAN(String pAN) {
            this.pAN = pAN;
            return this;
        }

        /**
         * Setter for usageRestrictionStatus.
         * @param  usageRestrictionStatus  String value for usageRestrictionStatus.
         * @return Builder
         */
        public Builder usageRestrictionStatus(String usageRestrictionStatus) {
            this.usageRestrictionStatus = usageRestrictionStatus;
            return this;
        }

        /**
         * Setter for usageRestrictionDescription.
         * @param  usageRestrictionDescription  String value for usageRestrictionDescription.
         * @return Builder
         */
        public Builder usageRestrictionDescription(String usageRestrictionDescription) {
            this.usageRestrictionDescription = usageRestrictionDescription;
            return this;
        }

        /**
         * Setter for dayTimeRestrictionStatus.
         * @param  dayTimeRestrictionStatus  String value for dayTimeRestrictionStatus.
         * @return Builder
         */
        public Builder dayTimeRestrictionStatus(String dayTimeRestrictionStatus) {
            this.dayTimeRestrictionStatus = dayTimeRestrictionStatus;
            return this;
        }

        /**
         * Setter for dayTimeRestrictionDescription.
         * @param  dayTimeRestrictionDescription  String value for dayTimeRestrictionDescription.
         * @return Builder
         */
        public Builder dayTimeRestrictionDescription(String dayTimeRestrictionDescription) {
            this.dayTimeRestrictionDescription = dayTimeRestrictionDescription;
            return this;
        }

        /**
         * Setter for productRestrictionStatus.
         * @param  productRestrictionStatus  String value for productRestrictionStatus.
         * @return Builder
         */
        public Builder productRestrictionStatus(String productRestrictionStatus) {
            this.productRestrictionStatus = productRestrictionStatus;
            return this;
        }

        /**
         * Setter for productRestrictionDescription.
         * @param  productRestrictionDescription  String value for productRestrictionDescription.
         * @return Builder
         */
        public Builder productRestrictionDescription(String productRestrictionDescription) {
            this.productRestrictionDescription = productRestrictionDescription;
            return this;
        }

        /**
         * Setter for locationRestrictionStatus.
         * @param  locationRestrictionStatus  String value for locationRestrictionStatus.
         * @return Builder
         */
        public Builder locationRestrictionStatus(String locationRestrictionStatus) {
            this.locationRestrictionStatus = locationRestrictionStatus;
            return this;
        }

        /**
         * Setter for locationRestrictionStatusDescription.
         * @param  locationRestrictionStatusDescription  String value for
         *         locationRestrictionStatusDescription.
         * @return Builder
         */
        public Builder locationRestrictionStatusDescription(
                String locationRestrictionStatusDescription) {
            this.locationRestrictionStatusDescription = locationRestrictionStatusDescription;
            return this;
        }

        /**
         * Setter for validationErrorCode.
         * @param  validationErrorCode  String value for validationErrorCode.
         * @return Builder
         */
        public Builder validationErrorCode(String validationErrorCode) {
            this.validationErrorCode = validationErrorCode;
            return this;
        }

        /**
         * Setter for validationErrorDescription.
         * @param  validationErrorDescription  String value for validationErrorDescription.
         * @return Builder
         */
        public Builder validationErrorDescription(String validationErrorDescription) {
            this.validationErrorDescription = validationErrorDescription;
            return this;
        }

        /**
         * Builds a new {@link RestrictioncardsRes} object using the set fields.
         * @return {@link RestrictioncardsRes}
         */
        public RestrictioncardsRes build() {
            return new RestrictioncardsRes(accountId, accountNumber, cardId, pAN,
                    usageRestrictionStatus, usageRestrictionDescription, dayTimeRestrictionStatus,
                    dayTimeRestrictionDescription, productRestrictionStatus,
                    productRestrictionDescription, locationRestrictionStatus,
                    locationRestrictionStatusDescription, validationErrorCode,
                    validationErrorDescription);
        }
    }
}
